// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSP_eOmqSmNdFeMgDFgT8R3oGWHzB1Ft4',
    appId: '1:342500747372:web:26d079c212dc2c01f99049',
    messagingSenderId: '342500747372',
    projectId: 'flutter-example-1b8ec',
    authDomain: 'flutter-example-1b8ec.firebaseapp.com',
    storageBucket: 'flutter-example-1b8ec.firebasestorage.app',
    measurementId: 'G-B831SLH96D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75uO3M8ANgGy9_2fta4UNFQX9zYmxpRM',
    appId: '1:342500747372:android:388219b170b6dfedf99049',
    messagingSenderId: '342500747372',
    projectId: 'flutter-example-1b8ec',
    storageBucket: 'flutter-example-1b8ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBE_fX5KV-28XCRuFK1y9uKy9eOYrAvOY',
    appId: '1:342500747372:ios:087f0d92f567a4c4f99049',
    messagingSenderId: '342500747372',
    projectId: 'flutter-example-1b8ec',
    storageBucket: 'flutter-example-1b8ec.firebasestorage.app',
    iosBundleId: 'com.example.flutterExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBE_fX5KV-28XCRuFK1y9uKy9eOYrAvOY',
    appId: '1:342500747372:ios:087f0d92f567a4c4f99049',
    messagingSenderId: '342500747372',
    projectId: 'flutter-example-1b8ec',
    storageBucket: 'flutter-example-1b8ec.firebasestorage.app',
    iosBundleId: 'com.example.flutterExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSP_eOmqSmNdFeMgDFgT8R3oGWHzB1Ft4',
    appId: '1:342500747372:web:8aaa936d8fcea2aef99049',
    messagingSenderId: '342500747372',
    projectId: 'flutter-example-1b8ec',
    authDomain: 'flutter-example-1b8ec.firebaseapp.com',
    storageBucket: 'flutter-example-1b8ec.firebasestorage.app',
    measurementId: 'G-T0EQDJD0WK',
  );
}
